package utils

import (
	"strings"

	"github.com/liuy/gbot/pkg/types"
)

// syntheticTexts contains message content strings generated by the system
// (not by the LLM) that should not count as "meaningful" assistant output.
var syntheticTexts = map[string]bool{
	types.InterruptMessage: true,
}

// IsSyntheticMessage returns true if the message's first content block is a
// text block matching a known synthetic string (interrupt, cancel, etc.).
func IsSyntheticMessage(msg types.Message) bool {
	if len(msg.Content) == 0 {
		return false
	}
	first := msg.Content[0]
	if first.Type != types.ContentTypeText {
		return false
	}
	return syntheticTexts[first.Text]
}

// IsToolUseResultMessage returns true for user messages whose first content
// block is a tool_result. These are API-structured, not user-authored text.
func IsToolUseResultMessage(msg types.Message) bool {
	if msg.Role != types.RoleUser || len(msg.Content) == 0 {
		return false
	}
	return msg.Content[0].Type == types.ContentTypeToolResult
}

// HasNonToolResultContent returns true if a user message has content blocks
// that are not tool_result (i.e., actual user text input).
func HasNonToolResultContent(msg types.Message) bool {
	for _, block := range msg.Content {
		if block.Type != types.ContentTypeToolResult {
			return true
		}
	}
	return false
}

// IsSelectableUserMessage returns true if the message is a user message
// selectable for rewind — contains actual user text, skipping tool_result,
// synthetic, compact summary, meta, attachment, and system-generated messages.
func IsSelectableUserMessage(msg types.Message) bool {
	if msg.Role != types.RoleUser {
		return false
	}
	if IsToolUseResultMessage(msg) {
		return false
	}
	if IsSyntheticMessage(msg) {
		return false
	}
	if msg.HasFlag(types.FlagCompactSummary) {
		return false
	}
	if msg.HasFlag(types.FlagMeta) {
		return false
	}
	if msg.MessageType == types.MessageTypeAttachment {
		return false
	}
	text := FirstTextBlockContent(msg)
	nonUserTags := []string{
		"<local-command-stdout>", "<local-command-stderr>",
		"<bash-stdout>", "<bash-stderr>",
		"<tick>", "<teammate-message>",
	}
	for _, tag := range nonUserTags {
		if strings.Contains(text, tag) {
			return false
		}
	}
	return !strings.Contains(text, "<job-notification>")
}

// LastSelectableUserMessageIndex returns the index of the last user message
// selectable for rewind, or -1 if none.
func LastSelectableUserMessageIndex(msgs []types.Message) int {
	for i := len(msgs) - 1; i >= 0; i-- {
		if IsSelectableUserMessage(msgs[i]) {
			return i
		}
	}
	return -1
}

// MessagesAfterAreOnlySynthetic returns true if all messages after msgs[idx]
// are non-meaningful (synthetic, tool_result carriers, or empty assistant).
func MessagesAfterAreOnlySynthetic(msgs []types.Message, fromIndex int) bool {
	for i := fromIndex + 1; i < len(msgs); i++ {
		msg := msgs[i]

		if IsSyntheticMessage(msg) {
			continue
		}

		if IsToolUseResultMessage(msg) {
			continue
		}

		switch msg.Role {
		case types.RoleUser:
			if HasNonToolResultContent(msg) {
				return false
			}
		case types.RoleAssistant:
			for _, block := range msg.Content {
				switch block.Type {
				case types.ContentTypeText:
					if strings.TrimSpace(block.Text) != "" {
						return false
					}
				case types.ContentTypeToolUse:
					return false
				}
			}
		}
	}
	return true
}

// FirstTextBlockContent returns the text of the first text content block,
// or empty string if none.
func FirstTextBlockContent(msg types.Message) string {
	for _, block := range msg.Content {
		if block.Type == types.ContentTypeText {
			return block.Text
		}
	}
	return ""
}
