// Package types defines shared types for gbot.
//
// Source reference: /home/yliu/claude-code-source-code/src/
// These types are ported 1:1 from the TypeScript source to ensure
// behavioral parity with the original Claude Code implementation.
package types

import (
	"encoding/json"
	"time"
)

// ---------------------------------------------------------------------------
// Message types — source: types/logs.ts, Tool.ts
// ---------------------------------------------------------------------------

// Role represents the role of a message sender.
type Role string

const (
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
)

// Message represents a single message in the conversation.
// Source: Anthropic API Message type + internal message extensions.
type Message struct {
	ID          string         `json:"id,omitempty"`
	Role        Role           `json:"role"`
	Content     []ContentBlock `json:"content"`
	Model       string         `json:"model,omitempty"`
	StopReason  string         `json:"stop_reason,omitempty"`
	Usage       *Usage         `json:"usage,omitempty"`
	Timestamp   time.Time      `json:"timestamp"`
	Flags       MessageFlag    `json:"flags,omitempty"`
	MessageType MessageType    `json:"message_type,omitempty"`
	Attachment  *Attachment    `json:"attachment,omitempty"`
}

// MessageFlag is a bitmask for message metadata flags.
// Source: TS message flags (isCompactSummary, isMeta, isVisibleInTranscriptOnly).
type MessageFlag uint

const (
	// FlagCompactSummary marks messages generated by the compact system
	// (boundary markers and conversation summaries).
	// Source: TS isCompactSummary in MessageSelector.tsx:780.
	FlagCompactSummary MessageFlag = 1 << iota

	// FlagMeta marks system-generated messages hidden from the UI.
	// Source: TS isMeta in MessageSelector.tsx:777.
	FlagMeta

	// FlagVisibleInTranscriptOnly marks messages visible only in transcript view.
	// Source: TS isVisibleInTranscriptOnly in MessageSelector.tsx:780.
	FlagVisibleInTranscriptOnly
)

// HasFlag checks if the message has a specific flag set.
func (m *Message) HasFlag(flag MessageFlag) bool {
	return m.Flags&flag != 0
}

// Usage tracks token consumption.
// Source: Anthropic API Usage type.
type Usage struct {
	InputTokens              int `json:"input_tokens"`                          // new (non-cached) input tokens
	OutputTokens             int `json:"output_tokens"`                         // output tokens
	CacheCreationInputTokens int `json:"cache_creation_input_tokens,omitempty"` // new tokens added to cache
	CacheReadInputTokens     int `json:"cache_read_input_tokens,omitempty"`     // tokens read from cache
}

// TotalInputTokens returns the total billed input tokens (new + cache read + cache create).
// Source: minimax cache docs — total = input + cache_read + cache_creation.
func (u Usage) TotalInputTokens() int {
	return u.InputTokens + u.CacheReadInputTokens + u.CacheCreationInputTokens
}

// SetMetadataFromJSON restores Usage/Model/StopReason/Flags/MessageType/Attachment from a JSON metadata string.
// Used by storage layer to deserialize the metadata column back into message fields.
func (m *Message) SetMetadataFromJSON(metadata string) {
	if metadata == "" {
		return
	}
	var meta struct {
		Usage       *Usage      `json:"usage,omitempty"`
		Model       string      `json:"model,omitempty"`
		StopReason  string      `json:"stop_reason,omitempty"`
		Flags       MessageFlag `json:"flags,omitempty"`
		MessageType MessageType `json:"message_type,omitempty"`
		Attachment  *Attachment `json:"attachment,omitempty"`
	}
	if err := json.Unmarshal([]byte(metadata), &meta); err == nil {
		m.Usage = meta.Usage
		m.Model = meta.Model
		m.StopReason = meta.StopReason
		m.Flags = meta.Flags
		m.MessageType = meta.MessageType
		m.Attachment = meta.Attachment
	}
}

// MetadataToJSON serializes Usage/Model/StopReason/Flags/MessageType/Attachment to a JSON metadata string.
// Returns empty string if no metadata fields are set.
func (m *Message) MetadataToJSON() string {
	if m.Usage == nil && m.Model == "" && m.StopReason == "" && m.Flags == 0 && m.MessageType == "" && m.Attachment == nil {
		return ""
	}
	meta := struct {
		Usage       *Usage      `json:"usage,omitempty"`
		Model       string      `json:"model,omitempty"`
		StopReason  string      `json:"stop_reason,omitempty"`
		Flags       MessageFlag `json:"flags,omitempty"`
		MessageType MessageType `json:"message_type,omitempty"`
		Attachment  *Attachment `json:"attachment,omitempty"`
	}{
		Usage:       m.Usage,
		Model:       m.Model,
		StopReason:  m.StopReason,
		Flags:       m.Flags,
		MessageType: m.MessageType,
		Attachment:  m.Attachment,
	}
	if b, err := json.Marshal(meta); err == nil {
		return string(b)
	}
	return ""
}

// ---------------------------------------------------------------------------
// ContentBlock types — source: Anthropic API ContentBlock variants
// ---------------------------------------------------------------------------

// ContentType identifies the type of a content block.
type ContentType string

const (
	ContentTypeText       ContentType = "text"
	ContentTypeToolUse    ContentType = "tool_use"
	ContentTypeToolResult ContentType = "tool_result"
	ContentTypeThinking   ContentType = "thinking"
	ContentTypeRedacted   ContentType = "redacted_thinking"
	ContentTypeImage      ContentType = "image"
	ContentTypeVideo      ContentType = "video"
)

// CacheControlConfig carries cache control settings for Anthropic API.
// Source: claude.ts:358-374
type CacheControlConfig struct {
	Type  string `json:"type"`            // "ephemeral"
	TTL   string `json:"ttl,omitempty"`   // "1h", "5m", etc.
	Scope string `json:"scope,omitempty"` // "global" | "org" | "" (none)
}

// ContentBlock is a discriminated union for message content.
// Source: Anthropic API content block types.
type ContentBlock struct {
	Type ContentType `json:"type"`

	// Text content (type == "text")
	Text string `json:"text,omitempty"`

	// Thinking content (type == "thinking")
	// Anthropic API requires "thinking" field (not "text") for thinking blocks.
	Thinking string `json:"thinking,omitempty"`
	// Signature is the Anthropic-issued opaque signature for thinking blocks.
	// Must be replayed verbatim; the API rejects modified signatures.
	// TS parity: claude.ts initializes signature: '' at content_block_start;
	// Go's zero value for string is automatic, so we rely on omitempty on send.
	Signature string `json:"signature,omitempty"`
	// ThinkingDurationNs records wall-clock thinking time in nanoseconds.
	// Set on thinking_end; not part of Anthropic API schema, not persisted.
	ThinkingDurationNs int64 `json:"-"`

	// Tool use fields (type == "tool_use")
	ID    string          `json:"id,omitempty"`
	Name  string          `json:"name,omitempty"`
	Input json.RawMessage `json:"input,omitempty"`

	// Tool result fields (type == "tool_result")
	ToolUseID string          `json:"tool_use_id,omitempty"`
	Content   json.RawMessage `json:"content,omitempty"`
	IsError   bool            `json:"is_error,omitempty"`

	// Redacted thinking data (type == "redacted_thinking")
	// Must be preserved verbatim and replayed to the API.
	Data string `json:"data,omitempty"`

	// Image content (type == "image")
	// Source: Anthropic API image content block — {type:"image", source:{type:"base64", media_type, data}}.
	Source *ImageSource `json:"source,omitempty"`

	// Cache control for incremental caching on the last block.
	// Source: claude.ts:3089-3106 — addCacheBreakpoints adds cache_control
	// only to the last block of the last message.
	CacheControl *CacheControlConfig `json:"cache_control,omitempty"`
}

// NewTextBlock creates a text content block.
func NewTextBlock(text string) ContentBlock {
	return ContentBlock{Type: ContentTypeText, Text: text}
}

// NewToolUseBlock creates a tool_use content block.
func NewToolUseBlock(id, name string, input json.RawMessage) ContentBlock {
	return ContentBlock{Type: ContentTypeToolUse, ID: id, Name: name, Input: input}
}

// NewToolResultBlock creates a tool_result content block.
func NewToolResultBlock(toolUseID string, content json.RawMessage, isError bool) ContentBlock {
	return ContentBlock{
		Type:      ContentTypeToolResult,
		ToolUseID: toolUseID,
		Content:   content,
		IsError:   isError,
	}
}

// ImageSource is the source payload of an image content block.
// Source: Anthropic API image block source — {type:"base64", media_type, data}.
//
// Two source types are supported:
//   - "base64": Data carries inline base64-encoded bytes (the only wire form
//     the Anthropic/OpenAI APIs accept).
//   - "file": Path references a local file that providers read and base64-
//     encode at request time (see llm.MaterializeFileImages). Used by the
//     WeChat connector to avoid storing large base64 blobs in the message DB.
type ImageSource struct {
	Type      string `json:"type"`           // "base64" | "file"
	MediaType string `json:"media_type"`     // "image/png", "image/jpeg", etc.
	Data      string `json:"data,omitempty"` // base64-encoded bytes (Type == "base64")
	Path      string `json:"path,omitempty"` // local file path (Type == "file")
}

// IsFileSource returns true if the source references a local file that must be
// read and base64-encoded at request time (Type == "file").
func (s *ImageSource) IsFileSource() bool { return s != nil && s.Type == "file" }

// NewImageBlock creates an image content block carrying base64-encoded image data.
func NewImageBlock(source ImageSource) ContentBlock {
	return ContentBlock{Type: ContentTypeImage, Source: &source}
}

// NewFileImageBlock creates an image content block referencing a local file.
// The provider reads and base64-encodes Path at request time (see
// llm.MaterializeFileImages). mediaType must be an image/* MIME type.
func NewFileImageBlock(mediaType, path string) ContentBlock {
	return ContentBlock{
		Type:   ContentTypeImage,
		Source: &ImageSource{Type: "file", MediaType: mediaType, Path: path},
	}
}

// ---------------------------------------------------------------------------
// Permission types — source: types/permissions.ts
// ---------------------------------------------------------------------------

// PermissionMode represents the current permission mode.
// Source: types/permissions.ts:16-22
type PermissionMode string

const (
	PermissionModeAcceptEdits PermissionMode = "acceptEdits"
	PermissionModeBypass      PermissionMode = "bypassPermissions"
	PermissionModeDefault     PermissionMode = "default"
	PermissionModeDontAsk     PermissionMode = "dontAsk"
	PermissionModePlan        PermissionMode = "plan"
	PermissionModeAuto        PermissionMode = "auto"
)

// PermissionBehavior represents the outcome of a permission check.
type PermissionBehavior string

const (
	BehaviorAllow       PermissionBehavior = "allow"
	BehaviorDeny        PermissionBehavior = "deny"
	BehaviorAsk         PermissionBehavior = "ask"
	BehaviorPassthrough PermissionBehavior = "passthrough"
)

// PermissionResult is the sum type for permission decisions.
// Source: types/permissions.ts:251-266
type PermissionResult interface {
	permissionResultMarker()
	Behavior() PermissionBehavior
}

// PermissionAllowDecision — source: types/permissions.ts:174-184
type PermissionAllowDecision struct{}

func (PermissionAllowDecision) permissionResultMarker()      {}
func (PermissionAllowDecision) Behavior() PermissionBehavior { return BehaviorAllow }

// PermissionAskDecision — source: types/permissions.ts:199-226
type PermissionAskDecision struct {
	Message string `json:"message"`
}

func (PermissionAskDecision) permissionResultMarker()      {}
func (PermissionAskDecision) Behavior() PermissionBehavior { return BehaviorAsk }

// PermissionDenyDecision — source: types/permissions.ts:231-236
type PermissionDenyDecision struct {
	Message string `json:"message"`
}

func (PermissionDenyDecision) permissionResultMarker()      {}
func (PermissionDenyDecision) Behavior() PermissionBehavior { return BehaviorDeny }

// ---------------------------------------------------------------------------
// Ask dialog types — unified permission + input requests
// ---------------------------------------------------------------------------

// UserDecision is the user's response to a permission ask dialog.
type UserDecision string

const (
	DecisionAllow       UserDecision = "allow"
	DecisionDeny        UserDecision = "deny"
	DecisionAllowAlways UserDecision = "allow_always"
)

// AskKind discriminates between permission and input ask events.
type AskKind string

const (
	AskPermission AskKind = "permission"
	AskInput      AskKind = "input"
)

// AskEvent carries a request from the engine to the TUI.
// Kind discriminates between permission asks and interactive input requests.
// The engine blocks on ResponseCh until the user responds.
type AskEvent struct {
	Kind AskKind
	// Permission-specific (AskPermission)
	ToolName   string          // tool being invoked (e.g. "Bash", "Write")
	Input      json.RawMessage // tool input JSON
	Message    string          // human-readable reason for the ask
	RuleDetail string          // matched rule description (e.g. "Bash(rm -rf *) from project")
	// Input-specific (AskInput)
	Prompt   string    // "[sudo] password for user:"
	Masked   bool      // password masking
	Deadline time.Time `json:"-"` // countdown timer for InputDialog (zero = no countdown)
	// Shared
	AgentType  string           // non-empty for sub-agent asks (e.g. "Explore")
	ResponseCh chan AskResponse `json:"-"` // engine reads, TUI writes
}

// AskResponse is the user's response to an AskEvent.
// For AskPermission: Decision is set (DecisionAllow/DecisionDeny/DecisionAllowAlways).
// For AskInput: Text is set with user input, or Aborted is true if cancelled.
type AskResponse struct {
	Decision UserDecision // permission response
	Text     string       // input response
	Aborted  bool         // user cancelled (input only)
	Timeout  bool         // dialog countdown expired (input only)
}

// ---------------------------------------------------------------------------
// Engine types — source: query.ts, QueryEngine.ts
// ---------------------------------------------------------------------------

// QueryEventType identifies the type of query event.
type QueryEventType string

const (
	// Query lifecycle
	EventQueryStart QueryEventType = "query_start"
	EventQueryEnd   QueryEventType = "query_end"

	// Per-round LLM turn
	EventTurnStart QueryEventType = "turn_start"
	EventTurnEnd   QueryEventType = "turn_end"

	// Thinking
	EventThinkingStart QueryEventType = "thinking_start"
	EventThinkingEnd   QueryEventType = "thinking_end"
	EventThinkingDelta QueryEventType = "thinking_delta"

	// Tool call lifecycle: start → param_delta → output_delta → end
	EventToolStart       QueryEventType = "tool_start"
	EventToolParamDelta  QueryEventType = "tool_param_delta"
	EventToolOutputDelta QueryEventType = "tool_output_delta"
	EventToolEnd         QueryEventType = "tool_end"

	// Text content lifecycle
	EventTextStart QueryEventType = "text_start"
	EventTextDelta QueryEventType = "text_delta"
	EventTextEnd   QueryEventType = "text_end"

	// Tool execution: EventToolRun signals input fully accumulated, execution starting.
	// Distinct from EventToolStart which signals the tool_use content block began streaming.
	EventToolRun    QueryEventType = "tool_run"
	EventUsage      QueryEventType = "usage"
	EventAttachment QueryEventType = "attachment"

	// Ask: engine requests user confirmation or input.
	EventAsk QueryEventType = "ask"

	// Retry: engine is retrying a failed stream attempt.
	EventRetryAttempt QueryEventType = "retry_attempt"

	// EventConnectorUserMessage carries a user message from an external connector
	// (WeChat) so the TUI can render it. The connector dispatches this BEFORE
	// calling engine.Query, because the TUI's own commitInput path already calls
	// AddUserMessage — reusing QueryStart would double-render.
	EventConnectorUserMessage QueryEventType = "connector_user_message"
)

// AgentMeta tags events originating from a sub-agent.
// When non-nil on a QueryEvent, the event comes from a child engine
// spawned by the Agent tool, not from the main engine.
type AgentMeta struct {
	ParentToolUseID string `json:"parent_tool_use_id,omitempty"`
	AgentType       string `json:"agent_type,omitempty"`
	Depth           int    `json:"depth,omitempty"`
}

// QueryEvent represents an event emitted during the query loop.
// In TS this is yielded by an async generator; in Go sent on a channel.
type QueryEvent struct {
	Type         QueryEventType     `json:"type"`
	Text         string             `json:"text,omitempty"`
	SessionID    string             `json:"session_id,omitempty"`
	ToolUse      *ToolUseEvent      `json:"tool_use,omitempty"`
	ToolResult   *ToolResultEvent   `json:"tool_result,omitempty"`
	Message      *Message           `json:"message,omitempty"`
	PartialInput *PartialInputEvent `json:"partial_input,omitempty"`
	Usage        *UsageEvent        `json:"usage_event,omitempty"`
	Agent        *AgentMeta         `json:"agent,omitempty"`
	Thinking     *ThinkingEvent     `json:"thinking,omitempty"`
	Ask          *AskEvent          `json:"ask,omitempty"`
	RetryAttempt *RetryAttemptEvent `json:"retry_attempt,omitempty"`
	Error        error              `json:"-"`
}

// UsageEvent carries token usage from the LLM provider during streaming.
type UsageEvent struct {
	InputTokens              int `json:"input_tokens"`
	OutputTokens             int `json:"output_tokens"`
	CacheReadInputTokens     int `json:"cache_read_input_tokens,omitempty"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens,omitempty"`
}

// ThinkingEvent carries thinking state information.
type ThinkingEvent struct {
	Duration time.Duration `json:"duration,omitempty"` // time spent thinking (set on ThinkingEnd)
	Text     string        `json:"text,omitempty"`     // thinking text delta (set on ThinkingDelta)
}

// RetryErrorType constants identify the category of stream failure for retry display.
type RetryErrorType string

const (
	RetryErrorStreamInterrupted RetryErrorType = "stream_interrupted"
	RetryErrorStreamEnded       RetryErrorType = "stream_ended"
)

// RetryAttemptEvent carries retry information when the engine retries a failed stream.
// Source: TS withRetry.ts — SystemAPIErrorMessage countdown display.
type RetryAttemptEvent struct {
	Attempt    int            `json:"attempt"`
	MaxRetries int            `json:"max_retries"`
	RetryInMs  int64          `json:"retry_in_ms"`
	ErrorType  RetryErrorType `json:"error_type,omitempty"`
	Error      string         `json:"error"`
}

// PartialInputEvent carries incremental input for a pending tool call.
type PartialInputEvent struct {
	ID       string `json:"id"`                // tool use ID
	Name     string `json:"name"`              // tool name (e.g. "Read", "Bash")
	Delta    string `json:"delta"`             // partial JSON string
	Summary  string `json:"summary,omitempty"` // pre-computed summary from engine
	IsSearch bool   `json:"is_search,omitempty"`
	IsRead   bool   `json:"is_read,omitempty"`
	IsList   bool   `json:"is_list,omitempty"`
	IsLsp    bool   `json:"is_lsp,omitempty"`
}

// ToolUseEvent represents a tool invocation event.
type ToolUseEvent struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Input    json.RawMessage `json:"input"`
	Summary  string          `json:"summary,omitempty"`   // pre-computed summary from engine
	IsSearch bool            `json:"is_search,omitempty"` // tool is a search operation (Grep, Glob, find)
	IsRead   bool            `json:"is_read,omitempty"`   // tool is a read operation (Read, cat)
	IsList   bool            `json:"is_list,omitempty"`   // tool is a list operation (ls, tree)
	IsLsp    bool            `json:"is_lsp,omitempty"`    // tool is an LSP operation
}

// ToolResultEvent represents a tool execution result event.
type ToolResultEvent struct {
	ToolUseID     string          `json:"tool_use_id"`
	Output        json.RawMessage `json:"output"`
	DisplayOutput string          `json:"display_output,omitempty"` // human-readable result for TUI
	IsError       bool            `json:"is_error,omitempty"`
	IsBackground  bool            `json:"is_background,omitempty"` // true = fork agent launched async
	IsSearch      bool            `json:"is_search,omitempty"`     // search/read/list classification for TUI
	IsRead        bool            `json:"is_read,omitempty"`
	IsList        bool            `json:"is_list,omitempty"`
	IsLsp         bool            `json:"is_lsp,omitempty"`
}

// ContinueReason indicates why the loop continues to another iteration.
type ContinueReason string

const (
	ContinueNextTurn       ContinueReason = "next_turn"
	ContinueMaxTokensRetry ContinueReason = "max_tokens_retry"
)

// LoopAction is the result of the transition decision tree.
type LoopAction struct {
	Continue bool
	Reason   ContinueReason
}

// ---------------------------------------------------------------------------
// Agent types — source: tools/AgentTool/builtInAgents.ts, AgentTool.tsx
// ---------------------------------------------------------------------------

// AgentSource identifies where an agent definition came from.
// Source: tools/AgentTool/loadAgentsDir.ts:136-159 — source field on BuiltIn/Custom/Plugin types.
type AgentSource string

const (
	AgentSourceBuiltIn         AgentSource = "built-in"
	AgentSourceUserSettings    AgentSource = "userSettings"
	AgentSourceProjectSettings AgentSource = "projectSettings"
	AgentSourcePolicySettings  AgentSource = "policySettings"
	AgentSourceFlagSettings    AgentSource = "flagSettings"
	AgentSourcePlugin          AgentSource = "plugin"
)

// AgentDefinition describes a built-in or custom agent type.
// Source: tools/AgentTool/loadAgentsDir.ts:106-133 — BaseAgentDefinition
type AgentDefinition struct {
	// Core fields
	AgentType       string
	WhenToUse       string
	SystemPrompt    func() string // lazily generated system prompt
	Tools           []string      // nil or ["*"] = all tools
	DisallowedTools []string      // blacklist
	Model           string        // "inherit" (use parent engine's model), tier name ("lite","pro","max"), or "provider/model"
	OmitClaudeMd    bool
	MaxTurns        int // 0 = no limit

	// Source tracking
	Source   AgentSource // where this definition came from
	Filename string      // original filename without .md extension (Source: loadAgentsDir.ts:656)
	BaseDir  string      // directory the .md was loaded from; "built-in" for built-ins

	// Future-ready fields (stored by Class 1, used by later classes)
	Skills                 []string          // skills — comma-separated from frontmatter
	Color                  string            // color — agent color name for TUI
	Effort                 string            // effort — "low","medium","high","max", or int as string
	PermissionModeField    PermissionMode    // permissionMode — validated against existing constants
	Background             bool              // background — always run as background job
	InitialPrompt          string            // initialPrompt — prepended to first user turn
	Memory                 string            // memory — "user","project","local"
	Isolation              string            // isolation — "worktree" (future)
	CriticalSystemReminder string            // criticalSystemReminder_EXPERIMENTAL
	RequiredMcpServers     []string          // requiredMcpServers
	McpServersRaw          []json.RawMessage // mcpServers — raw JSON for pkg/mcp to parse (avoids types→mcp cycle)
}

// AgentInput is the input parameters for the Agent tool.
// Source: AgentTool.tsx:82-138 — AgentToolInput
type AgentInput struct {
	Description     string `json:"description"`
	Prompt          string `json:"prompt"`
	SubagentType    string `json:"subagent_type,omitempty"`
	Name            string `json:"name,omitempty"`
	Model           string `json:"model,omitempty"`
	RunInBackground bool   `json:"run_in_background,omitempty"`
	Fork            bool   `json:"fork,omitempty"`
}

// SubQueryResult is the result returned by a sub-agent after execution.
// Source: agentToolUtils.ts:348-357 — AgentToolResult
type SubQueryResult struct {
	AgentID           string
	AgentType         string
	Content           string
	TotalDurationMs   int64
	TotalTokens       int
	TotalToolUseCount int
	AsyncLaunched     bool // true = fork agent launched in background
}

// ForkBoilerplateTag is the marker string used in fork agent directive messages
// to detect recursive forking. Source: forkSubagent.ts — FORK_BOILERPLATE_TAG
const ForkBoilerplateTag = "fork-boilerplate"

// InterruptMessage is appended inline to the assistant message when the user cancels.
// Source: TS INTERRUPT_MESSAGE — "[Request interrupted by user]".
const InterruptMessage = "[Request interrupted by user]"

// ---------------------------------------------------------------------------
// EventDispatcher — interface for routing events from Engine to consumers.
// Source: engine/EventDispatcher (moved here for dependency inversion)
// ---------------------------------------------------------------------------

// EventDispatcher is the interface for routing events from Engine to consumers.
// Engine depends on this abstraction rather than a concrete Hub type,
// following the Dependency Inversion Principle.
// *hub.Hub satisfies this interface.
type EventDispatcher interface {
	Dispatch(event QueryEvent)
}

// ---------------------------------------------------------------------------
// Skill system types
// Source: src/types/command.ts — Command / CommandBase / PromptCommand
// ---------------------------------------------------------------------------

// SkillSource identifies where a skill was loaded from.
// TS: SettingSource | 'builtin' | 'mcp' | 'plugin' | 'bundled'
type SkillSource string

const (
	SkillSourceBundled SkillSource = "bundled" // compiled-in skills
	SkillSourceUser    SkillSource = "user"    // ~/.gbot/skills/
	SkillSourceProject SkillSource = "project" // <gitroot>/.gbot/skills/
	SkillSourceManaged SkillSource = "managed" // /etc/gbot/skills/ (policy)
	SkillSourceMCP     SkillSource = "mcp"     // MCP server-provided
	SkillSourcePlugin  SkillSource = "plugin"  // plugin-provided
)

// SkillCommand represents a fully loaded and parsed skill.
// TS: CommandBase & PromptCommand — src/types/command.ts
type SkillCommand struct {
	// Identity — TS: CommandBase.name, description, aliases, userFacingName
	Name                 string
	DisplayName          string   // frontmatter "name" override
	Aliases              []string // TS: CommandBase.aliases
	Description          string
	WhenToUse            string // TS: whenToUse
	HasUserSpecifiedDesc bool   // TS: hasUserSpecifiedDescription

	// Content
	Content    string // body after frontmatter
	SourcePath string // absolute path to SKILL.md
	SourceDir  string // directory (for ${SKILL_DIR})
	Source     SkillSource
	LoadedFrom string // "skills" | "bundled" | "mcp" | "plugin"

	// Execution control — TS: PromptCommand fields
	Type                   string   // "prompt" (default)
	AllowedTools           []string // nil = all tools
	Model                  string   // "", "inherit", "haiku", etc.
	Effort                 string   // "low"/"medium"/"high"/"max"
	Context                string   // "" (inline, default) or "fork"
	DisableModelInvocation bool
	IsUserInvocable        bool // default true; false = agent-only
	DisableNonInteractive  bool // TS: disableNonInteractive
	Immediate              bool // TS: immediate — bypasses queue
	IsSensitive            bool // TS: isSensitive — args redacted in history

	// Arguments — TS: argumentHint, argNames, arguments
	ArgumentHint string
	Arguments    []SkillArgument

	// Conditional activation — TS: PromptCommand.paths
	Paths []string // glob patterns

	// Hooks — TS: PromptCommand.hooks
	Hooks map[string]any // lifecycle hooks

	// Shell — TS: parseShellFrontmatter
	Shell *string // "bash"|"powershell"; nil = bash

	// Auth gating — TS: CommandBase.availability
	Availability []string // "claude-ai"|"console"

	// Plugin info — TS: PromptCommand.pluginInfo
	PluginInfo *PluginSkillInfo

	// Dynamic enablement — TS: CommandBase.isEnabled
	IsEnabledFunc func() bool

	// Metadata
	Version         string
	ProgressMessage string // TS: progressMessage (default: "running")
	ContentLength   int    // TS: contentLength
	SkillRoot       string // TS: skillRoot (for CLAUDE_PLUGIN_ROOT env)

	// AgentType — TS: frontmatter.agent — fork skills use this to select sub-agent type.
	AgentType string
}

// IsHidden returns true if the skill is not user-invocable.
// TS: loadSkillsDir.ts:335 — isHidden = userInvocable === false
func (c *SkillCommand) IsHidden() bool { return !c.IsUserInvocable }

// UserFacingName returns the display name.
// TS: getCommandName() → userFacingName || name
func (c *SkillCommand) UserFacingName() string {
	if c.DisplayName != "" {
		return c.DisplayName
	}
	return c.Name
}

// MeetsAvailabilityRequirement checks auth gating.
// TS: commands.ts:417-443
func (c *SkillCommand) MeetsAvailabilityRequirement() bool {
	if len(c.Availability) == 0 {
		return true
	}
	// gbot has no auth tiers, so all availability requirements pass.
	return true
}

// PluginSkillInfo holds plugin metadata.
// TS: command.ts:33-36 pluginInfo
type PluginSkillInfo struct {
	PluginName string
	Repository string
}

// SkillArgument defines a single skill argument.
// TS: argNames from arguments frontmatter field
type SkillArgument struct {
	Name        string
	Description string
	Required    bool
	Default     string
}

// InvokedSkillInfo tracks skills that have been invoked for compaction protection.
// TS: state.ts InvokedSkillInfo
type InvokedSkillInfo struct {
	SkillName string
	SkillPath string // e.g., "project:commit"
	Content   string // full expanded content
	InvokedAt time.Time
	AgentID   string // scoping key for sub-agents
}

// CommandPermissionsAttachment represents tool/model permissions granted by a skill.
// TS: attachments.ts:604-608 — {type: 'command_permissions', allowedTools, model}
// gbot does not have an AttachmentMessage system; this is conveyed via XML user message.
type CommandPermissionsAttachment struct {
	AllowedTools []string
	Model        string
}
