package wui

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// RegisterArtifactRoutes mounts GET /artifacts/{name...} serving files from
// dir (the projectspace artifacts directory). Registered patterns are more
// specific than the SPA catch-all "/", so they win during mux matching.
func RegisterArtifactRoutes(mux *http.ServeMux, dir string) {
	mux.HandleFunc("GET /artifacts/{name...}", func(w http.ResponseWriter, r *http.Request) {
		full, status := artifactFilePath(dir, r.PathValue("name"))
		if status != 0 {
			http.Error(w, http.StatusText(status), status)
			return
		}
		// allow-same-origin: the document shares the wui origin, so
		// localStorage/fullscreen/dialogs work (the user explicitly trusts
		// artifact content — all of it is generated by this agent).
		// Cross-origin resources stay blocked by default-src; the blast
		// radius of an injected page is capped at this origin.
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Content-Security-Policy", "default-src 'self' 'unsafe-inline' data:; sandbox allow-scripts allow-same-origin")
		w.Header().Set("X-Frame-Options", "SAMEORIGIN")

		f, err := os.Open(full)
		if err != nil {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		defer f.Close()
		st, err := f.Stat()
		if err != nil || st.IsDir() {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		// Zero modtime: ServeContent emits no Last-Modified and never
		// negotiates a 304 — combined with no-store this guarantees an
		// iframe reload always fetches fresh content.
		http.ServeContent(w, r, st.Name(), time.Time{}, f)
	})
}

// artifactFilePath resolves an artifact name under dir. PathValue is
// already percent-decoded, which is why encoded traversal (%2e%2e%2f) is
// caught by the same ".." segment check as its literal form. The prefix
// re-check after Join is belt-and-braces against any name that cleans to
// dir itself or escapes it.
func artifactFilePath(dir, name string) (string, int) {
	if name == "" {
		return "", http.StatusBadRequest
	}
	for _, seg := range strings.Split(name, "/") {
		if seg == ".." {
			return "", http.StatusBadRequest
		}
	}
	full := filepath.Join(dir, filepath.FromSlash(name))
	if !strings.HasPrefix(full, dir+string(os.PathSeparator)) {
		return "", http.StatusBadRequest
	}
	return full, 0
}
