package tui

import (
	"fmt"
	"log/slog"
	"strings"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/liuy/gbot/pkg/engine"
	"github.com/liuy/gbot/pkg/types"
)

// ---------------------------------------------------------------------------
// Auto-rewind — ESC cancel when LLM produced no meaningful content
// Source: TS REPL.tsx:2996-3022 — restoreMessageSync
// ---------------------------------------------------------------------------

// syntheticTexts contains message content strings that are generated by the system
// (not by the LLM) and should not count as "meaningful" assistant output.
// Source: TS utils/messages.ts — SYNTHETIC_MESSAGES set.
var syntheticTexts = map[string]bool{
	types.InterruptMessage: true, // "[Request interrupted by user]"
	// TS also has INTERRUPT_MESSAGE_FOR_TOOL_USE, CANCEL_MESSAGE, REJECT_MESSAGE,
	// NO_RESPONSE_REQUESTED. gbot only uses InterruptMessage and reject messages.
	// Reject messages are injected as tool_result content, not as assistant text blocks,
	// so they don't need to be here.
}

// messagesAfterAreOnlySynthetic checks if all messages after msgs[idx] are
// non-meaningful. Returns true if no meaningful assistant text or tool_use
// blocks exist after the given index.
//
// Adapted from TS MessageSelector.tsx:799-843 — messagesAfterAreOnlySynthetic.
// gbot's types.Message only has Role + Content blocks, so the predicate is simplified:
//   - TS msg.type === 'assistant' → Go msg.Role == types.RoleAssistant
//   - TS block.type === 'text' → Go block.Type == types.ContentTypeText
//   - TS block.type === 'tool_use' → Go block.Type == types.ContentTypeToolUse
//   - TS isSyntheticMessage → syntheticTexts check on first text block
//   - TS .isMeta / .isCompactSummary → not applicable (gbot doesn't have these)
func messagesAfterAreOnlySynthetic(msgs []types.Message, fromIndex int) bool {
	for i := fromIndex + 1; i < len(msgs); i++ {
		msg := msgs[i]

		// Skip synthetic messages (interrupt, cancel, reject, etc.)
		// Source: TS isSyntheticMessage — checks first text block against SYNTHETIC_MESSAGES
		if isSyntheticMessage(msg) {
			continue
		}

		switch msg.Role {
		case types.RoleUser:
			// User messages are only synthetic if they contain only tool_result blocks
			if hasNonToolResultContent(msg) {
				return false
			}
		case types.RoleAssistant:
			// Check for meaningful content: non-empty text or tool_use blocks
			for _, block := range msg.Content {
				switch block.Type {
				case types.ContentTypeText:
					if strings.TrimSpace(block.Text) != "" {
						return false // meaningful text content
					}
				case types.ContentTypeToolUse:
					return false // tool use is meaningful
				}
			}
		}
	}
	return true
}

// isSyntheticMessage returns true if the message's first text block matches a known
// synthetic string (interrupt, cancel, etc.). These are system-generated messages that
// should not count as meaningful LLM output.
// Source: TS utils/messages.ts:310-319 — isSyntheticMessage.
func isSyntheticMessage(msg types.Message) bool {
	for _, block := range msg.Content {
		if block.Type == types.ContentTypeText {
			return syntheticTexts[block.Text]
		}
	}
	return false
}

// hasNonToolResultContent returns true if a user message has content blocks
// that are not tool_result (i.e., actual user text input).
func hasNonToolResultContent(msg types.Message) bool {
	for _, block := range msg.Content {
		if block.Type != types.ContentTypeToolResult {
			return true
		}
	}
	return false
}

// lastUserMessageIndex returns the index of the last user message, or -1.
func lastUserMessageIndex(msgs []types.Message) int {
	for i := len(msgs) - 1; i >= 0; i-- {
		if msgs[i].Role == types.RoleUser {
			return i
		}
	}
	return -1
}

// firstTextBlockContent returns the text of the first ContentTypeText block, or "".
func firstTextBlockContent(msg types.Message) string {
	for _, block := range msg.Content {
		if block.Type == types.ContentTypeText {
			return block.Text
		}
	}
	return ""
}

// tryAutoRewind attempts to rewind on abort if no meaningful response was received.
// Returns true if rewind happened (messages truncated + input restored).
//
// Only called for main engine aborts (not sub-agents).
// Source: TS restoreMessageSync in REPL.tsx
func (a *App) tryAutoRewind() bool {
	msgs := a.engine.Messages()
	lastUserIdx := lastUserMessageIndex(msgs)
	if lastUserIdx < 0 {
		return false
	}

	if !messagesAfterAreOnlySynthetic(msgs, lastUserIdx) {
		return false // assistant produced meaningful output
	}

	// Extract user text for input restoration
	userText := firstTextBlockContent(msgs[lastUserIdx])

	// Rewind engine messages + file history
	result, err := a.engine.RewindTo(lastUserIdx)
	if err != nil {
		slog.Error("tui:auto_rewind:engine_failed", "err", err)
		return false
	}
	_ = result

	// Sync store: remove persisted messages that were rewound.
	// Without this, resume reloads orphaned messages from store.
	if a.store != nil && a.sessionID != "" && a.lastPersistedIdx > 0 {
		_ = a.store.TruncateMessagesFromIndex(a.sessionID, 0)
		a.lastPersistedIdx = 0
	}
	// Truncate TUI messages to committedCount (current turn was not committed)
	if a.committedCount <= len(a.repl.messages) {
		a.repl.messages = a.repl.messages[:a.committedCount]
	}
	if a.committedCount > len(a.repl.messages) {
		a.committedCount = len(a.repl.messages)
	}

	// Restore input text so user can edit and resubmit
	a.input.SetValue(userText)

	// Remove history entry for the cancelled query
	if a.history != nil {
		a.history.RemoveLast()
	}

	a.markViewportDirty()
	return true
}

// ---------------------------------------------------------------------------
// /rewind command — message picker dialog + file restoration
// Source: TS /rewind → MessageSelector.tsx
// ---------------------------------------------------------------------------

// handleRewind opens a message picker dialog to select a rewind target.
// If the selected rewind point has file changes, a second dialog lets the user
// choose between restoring code only, conversation only, or both.
// Source: TS /rewind → MessageSelector.tsx → getRestoreOptions
func (a *App) handleRewind(commitCmd tea.Cmd) tea.Cmd {
	if a.repl.IsStreaming() {
		return commitCmd
	}

	msgs := a.engine.Messages()

	var options []DialogOption
	var indices []int
	for i, msg := range msgs {
		if msg.Role != types.RoleUser {
			continue
		}
		text := firstTextBlockContent(msg)
		if text == "" {
			continue
		}
		label := fmt.Sprintf("%s  %s", msg.Timestamp.Format("15:04"), truncateRunes(text, 60))
		options = append(options, DialogOption{Label: label})
		indices = append(indices, i)
	}

	if len(options) == 0 {
		return commitCmd
	}

	a.activeDialog = NewDialog("Rewind to message:", options)
	a.activeDialog.width = a.width

	a.onDialogDone = func(d *Dialog) (tea.Model, tea.Cmd) {
		if d.Aborted() {
			return a, a.readEvents()
		}
		idx := indices[d.SelectedIndex()]

		// TS align: MessageSelector.tsx uses preselectedMessage.uuid directly
		// for fileHistoryGetDiffStats. No fallback, no backwards search.
		var hasFileChanges bool
		if a.fileHistory != nil && idx < len(msgs) {
			checkMsgID := msgs[idx].ID
			hasFileChanges = a.fileHistory.HasChangesAtMessage(checkMsgID)
			slog.Info("tui:rewind_filecheck", "idx", idx, "checkMsgID", checkMsgID, "hasFileChanges", hasFileChanges)
		}

		if !hasFileChanges {
			// No file changes — rewind messages only directly
			return a.executeRewind(idx, engine.RewindMessagesOnly, msgs)
		}

		// File changes exist — show scope selection dialog
		// Source: TS MessageSelector.tsx getRestoreOptions — canRestoreCode_0 check
		scopeOpts := []DialogOption{
			{Label: "Restore code and conversation"},
			{Label: "Restore conversation"},
			{Label: "Restore code"},
			{Label: "Cancel"},
		}

		a.activeDialog = NewDialog("What do you want to restore?", scopeOpts)
		a.activeDialog.width = a.width

		a.onDialogDone = func(d *Dialog) (tea.Model, tea.Cmd) {
			if d.Aborted() {
				return a, a.readEvents()
			}
			selected := d.SelectedIndex()
			switch selected {
			case 0: // Restore code and conversation
				return a.executeRewind(idx, engine.RewindAll, msgs)
			case 1: // Restore conversation only
				return a.executeRewind(idx, engine.RewindMessagesOnly, msgs)
			case 2: // Restore code only
				return a.executeRewind(idx, engine.RewindFilesOnly, msgs)
			default: // Cancel
				return a, a.readEvents()
			}
		}
		return a, a.readEvents()
	}
	return commitCmd
}

// executeRewind performs the actual rewind with the given scope.
// Source: TS MessageSelector.tsx onSelectRestoreOption
func (a *App) executeRewind(idx int, scope engine.RewindScope, originalMsgs []types.Message) (tea.Model, tea.Cmd) {
	result, err := a.engine.RewindToScoped(idx, scope)
	if err != nil {
		slog.Error("tui:rewind:engine_failed", "err", err)
		return a, a.readEvents()
	}

	if len(result.RestoredFiles) > 0 {
		slog.Info("tui:rewind:files_restored", "count", len(result.RestoredFiles), "files", result.RestoredFiles)
	}

	// Sync persistence for message-affecting scopes
	if scope == engine.RewindAll || scope == engine.RewindMessagesOnly {
		if a.store != nil && a.sessionID != "" && idx < a.lastPersistedIdx {
			_ = a.store.TruncateMessagesFromIndex(a.sessionID, idx)
			a.lastPersistedIdx = idx
		}
		// Reset TUI messages — rewind changes engine messages, rebuild from scratch
		*a.repl = *NewReplState()
		a.committedCount = 0
		// Restore input text from the selected message for resubmission
		selectedText := firstTextBlockContent(originalMsgs[idx])
		a.input.SetValue(selectedText)
	}

	a.markViewportDirty()
	slog.Info("tui:rewind", "to_index", idx, "scope", scope, "message_count", result.MessageCount)
	return a, a.readEvents()
}
